jumptrading/influx-spout

- README.md
- config/config.go
- config/config_small_test.go
- filter/filter.go
- filter/filter_medium_test.go
- filter/rules_small_test.go
- filter/timestamp_small_test.go
- filter/worker.go
- perfcheck
A new "max_time_delta_secs" configuration option has been added. If the filter sees a line with a timestamp which is outside ±max_time_delta_secs around the current time it will be reject. A new metric has been added to the filter which counts these rejected lines.
This feature adds a 3-5% performance hit to the filter ProcessBatch benchmark, although this is largely lost when compared to the cost of matching any realistic number of filter rules (i.e. regex matching is expensive).
Fixes #27.
> Rejection of invalid timestamps 

- writer/writer_medium_test.go
Don't share test infrastructure between the various writer tests to avoid inter-test interference and confusing test failures.
> writer: Clean up tests

- filter/filter.go
The alias `/nats` breaks the build in a vanilla environment as that isn't vendored in.
> filter: Changed NATS import to use the correct path

- filter/worker.go
Timestamp + 6 bytes is the shortest possible measurement line.
`a b=c [timestamp]`
> filter: Incremented the minimum line length threshold

- README.md
I noticed that the TravisCI badge was no longer correct since the repo became public.
> Update TravisCI badge now that project is public

- perfcheck
TravisCI does a single branch clone of the repository which means the perfcheck reference revision isn't necessarily available.  perfcheck now explicitly fetches the revision it needs.
> Pull perfcheck reference branch from origin

- cmd/run.go
- monitor/monitor.go
- monitor/monitor_medium_test.go
- prometheus/metric.go
- prometheus/metricset.go
- prometheus/metricset_small_test.go
- prometheus/parse.go
- prometheus/parse_small_test.go
This PR adds a new "monitor" component which accumulates metrics from the NATS monitor subject
and makes them available in Prometheus' data exposition format via a HTTP endpoint. The monitor is functional and tested but the other modes still need to be changed to send their metrics in Prometheus format as required by the monitor (coming soon).
A number of additions were made to the prometheus package to support this change.
Still to come:
- have all influx-spout components send using Prometheus format
- manually test with telegraf
- integrate into end-to-end test
- update README to describe the monitor (diagram too)
Part of the work for #29.
> Introduce monitor component

- perfcheck
The reference revision fetched in the "current" repo didn't always make it across when cloning to the reference repo, resulting in "reference is not a tree" errors from git.
> perfcheck: Fetch reference branch in reference clone

- monitor/monitor.go
NATS subscriptions don't seem to take immediate effect unless the NATS connection is flushed first. Not flushing was causing spurious test failures.
> monitor: Flush after subscribing

- benchcheck/benchcheck.go
- perfcheck
To mitigate against the variation in performance in TravisCI's test environment, perfcheck will now try multiple attempts at passing. Each attempt is 3 iterations of benchmark runs.
This increases the chances of success and makes the overall test run time shorter if the first attempt passes.
perfcheck now also has benchcheck print the results table. While we're working through perfcheck changes it's useful to always see the benchmark comparison from benchcheck.
> perfcheck tweaks

- listener/listener.go
... and added some missing docstrings for public types/methods.
> listener: Remove unused state metrics

- spouttest/influxd.go
- writer/writer_medium_test.go
Two fake influxd types have been implemented for use in tests. The funcs which started them would sometimes return before the fake server was listening, causing test failures. The start funcs now wait for the listener to have started before returning, eliminating occasional spurious test failures.
> Wait for fake influxd to have started

- spouttest/e2e_test.go
- stats/stats.go
- stats/stats_small_test.go
- writer/writer.go
This metric reports the maximum number of pending bytes observed across all a writer's NATS subscriptions. This can be used to help tune the `nats_pending_max_mb` configuration option.
To assist with generating this metric `stats.Stats` now supports tracking of maximum values.
Closes #31.
> New writer max_pending metric

- filter/filter.go
- filter/filter_medium_test.go
- spouttest/e2e_test.go
This introduces a new `nats_dropped` filter metric which reports when the filter has lost incoming NATS messages.
> filter: Expose NATS dropped messages metric

- filter/filter.go
- filter/filter_medium_test.go
- filter/worker.go
- spouttest/e2e_test.go
Previously, errors while publishing to NATS were being silently ignored. This now increments the new metric and generates logs if Debug is enabled.
> filter: New "failed_nats_publish" metric

- filter/filter.go
- listener/listener.go
- monitor/monitor.go
- writer/writer.go
The NATS connections created by the filter and monitor weren't set to keep retrying and were using the default reconnection limit of 60.
The listener and writer were using infinite NATS reconnection attempts but were setting this up in an undocumented way (which may not always have worked).
> Always retry connections to NATS

- README.md
- filter/filter.go
- filter/filter_medium_test.go
- writer/writer.go
As for the writer, the filter now uses the `nats_pending_max_mb` configuration option to set the maximum pending buffer size for the incoming NATS subject. Previously it was using the default size of 65MB. Using a higher number may help to prevent dropped messages in the filter. The default is 200MB.
> filter: Use nats_pending_max_mb

- spouttest/e2e_test.go
- writer/writer.go
- Always report drop counts for each subscription, instead of only when a drop is detected.
- Move the responsibility for reporting NATS drops to the statistician. This avoids a goroutine per subscription (which was probably overkill) and simplifies the code.
- Removed a lot of logging that was of dubious value (the metric provides the same information and scales better)
> writer: Clean up subscription dropped reporting

- listener/listener.go
- listener/listener_medium_test.go
- spouttest/e2e_test.go
This increments if the listener fails to publish lines to NATS (for consumption by the filter).
Closes #19 .
> listener: Add `failed_nats_publish` metric

- README.md
- filter/filter.go
The filter now subscribes to its inbound NATS subject using a queue group so that multiple filters can be run at the same time.
Closes #55.
I've tested this with parallel filters, ensuring that all lines injected into the listener make it through to the database exactly once.
> filter: Allow for multiple filters

- README.md
- config/config.go
- config/config_small_test.go
- filter/filter.go
- filter/filter_medium_test.go
- listener/listener.go
- listener/listener_medium_test.go
- monitor/monitor.go
- monitor/monitor_medium_test.go
- probes/probes.go
- probes/probes_medium_test.go
- spouttest/asserts.go
- spouttest/e2e_test.go
- writer/writer.go
- writer/writer_medium_test.go
The listener, filter, writer and monitor components now all expose Kubernetes compatible `/healthz` and `/readyz` HTTP endpoints (if `probe_port` is set in configuration). See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/.
All tests now use the endpoints to synchronise component startup. The "Ready" channels that were exposed by some components have been removed.
Closes #53.
> Expose k8s probe endpoints for all components

- listener/batch.go
- listener/listener.go
- listener/listener_medium_test.go
This fixes an issue where a large HTTP POST, or a POST which arrives when the batch buffer is nearly full could get split, corrupting one of the lines contained within it.
Part of the fix involves cleaning up the way the batch buffer is handled, normalising the way reads for UDP and HTTP are done and separating batch buffer handling concerns from the main listener code.
The batch buffer will now be grown if required to support any HTTP POST that arrives. Growing the batch buffer is expensive and the listener is arranged to minimise the chance of the buffer needing to grow at all. Growing the buffer is a fallback.
> listener: Prevent large HTTP POSTs from being broken up 

- listener/listener.go
Telegraf HTTP InfluxDB output throws an error if Spout HTTP listener returns a 200 instead of 204 (StatusNoContent). The latter is the standard "OK" response from InfluxDB. 
```
E! InfluxDB Output Error: Response Error: Status Code [200], expected [204], [<nil>]
```
> listener: Changed succesful HTTP response code from 200 to 204

- filter/timestamp_small_test.go
- filter/worker.go
- influx/timestamps.go
- influx/timestamps_small_test.go
- listener/batch.go
- listener/listener.go
- listener/listener_medium_test.go
The HTTP listener component now supports an optional `precision` argument which specifies the precision of the timestamps being sent. This mimics a similar feature of InfluxDB itself. Care has been taken to minimise the performance impact of this change and a fast path is used if nanosecond precision is in use.
To support this change there's been some cleanup of influx-spout's timestamp handling functionality. Benchmarks for the HTTP listener have also been added to guard against future regressions.
Closes #72.
> Add support for HTTP "precision" parameter

- filter/rules_small_test.go
- listener/listener_medium_test.go
- perfcheck
- spouttest/logs.go
- writer/writer_medium_test.go
The logs are messing up the output meaning that perfcheck isn't able to compare some benchmarks.
Also:
* Removed the manual filtering of the `vendor` directory in perfcheck. Modern Go versions do this by default.
* Avoid unnecessary use of TestMain in listener tests. TestMain isn't really necessary, is a little confusing and it's best to isolate the gnatsd instance for each test for reliability reasons.
Once this lands, I'll merge the benchmark log suppression change into the `perfcheck-reference` branch so that all benchmarks are being compared again.
> Disable benchmark logs

- README.md
- cmd/run.go
- config/config.go
- config/config_small_test.go
- writer/writer.go
Instead of having pprof support hardcoded into just the writer, allow the port to be specified via the configuration.
> Implement pprof support

- filter/filter.go
- filter/rules_small_test.go
- filter/worker.go
- listener/listener.go
- stats/anonstats.go
- stats/anonstats_test.go
- stats/stats.go
- stats/stats_small_test.go
Profiling had revealed that a surprising amount of time was being spent in the filter converting rule indexes to the generated stat names. There was also a reasonable amount of time being spent waiting for the stats.Stats mutex. Using a stats.AnonStats instead solves both these issues.
AnonStats maintains a set of counters. It differs from Stats in the following ways:
- each counter is indexed by an integer instead of by name, avoiding the need for map lookups
- goroutine safety is achieved through the use of sync/atomic primitives instead of a global mutex. This is faster and avoids the problem of unnecessary synchronization between goroutines.
- counter values are uint64 instead of int
Stats now simply provide names for the index based counters contained in an embedded AnonStats. This …
> Improve stats performance

- Gopkg.lock
- Gopkg.toml
- HACKING.md
- README.md
- cmd/influx-spout/e2e_large_test.go
- config/config.go
- config/config_small_test.go
- config/duration.go
- filter/filter.go
- filter/filter_medium_test.go
- filter/worker.go
- listener/listener.go
- listener/listener_medium_test.go
- tools/listener.toml
- tools/listener_http.toml
- tools/writer.toml
- vendor/github.com/c2h5oh/datasize/.gitignore
- vendor/github.com/c2h5oh/datasize/.travis.yml
- vendor/github.com/c2h5oh/datasize/LICENSE
- vendor/github.com/c2h5oh/datasize/README.md
- vendor/github.com/c2h5oh/datasize/datasize.go
- vendor/github.com/c2h5oh/datasize/datasize_test.go
- writer/writer.go
- writer/writer_medium_test.go
This is a significant rationalisation of influx-spout's configuration and breaks backwards compatibliity. Highlights:
* bytes sizes are now represented internally using a specialised type and are parsed from strings which may have unit suffixes (e.g. `"200MB"`)
* The listener_batch_size option has been removed. The listener now uses the `batch_max_size` option for this (these options had the same purpose but were previously separate due to scaling issues).
* Time duration based values are now represented using a time.Duration and are parsed from user friendly strings (e.g. `"5m"` and `"30s"`) instead of being fixed in seconds.
* The `batch` option has been renamed to the more descriptive `batch_max_count`.
Summary of configuration fields renamed in this PR:
- batch_max_mb -> …
> Configuration cleanup

- cmd/influx-spout/e2e_large_test.go
- filter/filter.go
- filter/filter_medium_test.go
- listener/listener.go
- listener/listener_medium_test.go
- monitor/monitor_medium_test.go
- prometheus/labels.go
- prometheus/labels_small_test.go
- prometheus/metric.go
- prometheus/metric_small_test.go
- prometheus/metricset_small_test.go
- prometheus/parse.go
- prometheus/parse_small_test.go
- stats/prometheus.go
- stats/prometheus_small_test.go
- writer/writer.go
- writer/writer_medium_test.go
* Rename prometheus.LabelPair(s) to Label(s)  (better name)
* Added tests for Labels and Labels
* Added `With()` method to Labels 
* Pass labels around as `prometheus.Labels` instead of a map. This is more convenient and avoid unnecessary conversion.
* New `stats.NewLabels()` func for creating the base set of labels reported by all components.
* Include the hostname in the base set of labels.
Closes #89.
> Include hostname in Prometheus metrics

- config/config.go
- config/config_small_test.go
A number of possible configuration errors are detected and more checks can be added as required.
Closes #30.
> Introduce configuration validation

- README.md
- config/config.go
- config/config_small_test.go
- filter/filter.go
- listener/listener.go
- listener/listener_medium_test.go
- writer/writer.go
It was fixed at 3s but can now be set via new `stats_interval` configuration option.
Fixes #35.
> Make stats publish interval configurable

- README.md
There were a couple of missing octothorps.
> Fix invalid TOML in README

- filter/rules.go
- filter/rules_small_test.go
Avoid expensive unescaping of measurement names when they don't need unescaping. This improves filter benchmarks that involve a basic filter rule.
> filter: Avoid unnecessary unescaping for basic rules

- README.md
- config/config.go
- config/config_small_test.go
- filter/rules.go
- filter/rules_small_test.go
This allows matching against one or more exact tags on measurement
lines. The approach taken is much faster than using regexes to achieve
the same kinds of matches (80-1000% depending on number tags to match
and size of line). This approach is also much safer as matching is
independent of tag order and matches tag keys and values precisely.
This change features some nice improvements in how line parsing is
done in the filter.
Closes #90.
> Introduce new "tags" filter rule type

- convert/convert.go
- convert/convert_small_test.go
- influx/timestamps_small_test.go
This is required to support the upcoming measurement downsampling feature (#100)
> convert: ToInt now supports negative numbers

- cmd/influx-spout/e2e_large_test.go
- filter/filter_medium_test.go
- filter/rules.go
- filter/rules_small_test.go
- filter/worker.go
- influx/escape.go
- influx/escape_small_test.go
- influx/tags.go
- influx/tags_small_test.go
- influx/token.go
- influx/token_small_test.go
- influx/unescape.go
- influx/unescape_small_test.go
The filter now orders tag keys in all measurement lines passing through it (if required). This is required to support the upcoming downsampler feature (#100) and also helps InfluxDB efficiency.
Even though unnecessary computation, memory allocations and memory copies have been avoided where possible this has a negative impact on filter performance. According to perfcheck, the impact is visible but not enough to trigger a performance regression failure.
Extensive refactoring of the filter's line protocol parsing routines were made to support this change. Most of this functionality now resides in the `influx` package. All this is required for the upcoming downsampler feature.
> Implement tag ordering

- influx/escape.go
- influx/escape_small_test.go
Takes a string value and wraps it in double quotes, escaping any double quotes contained within it.
This is part of the work for #100.
> influx: Added EscapeQuotedString

- downsampler/assigner.go
- downsampler/assigner_small_test.go
- downsampler/avgbucket.go
- downsampler/avgbucket_small_test.go
This includes timestamp range errors as well as any other line handling errors.
> downsampler: Include original lines in line errors

- perfcheck
There have been a number of benchmarks added and performance is stable
so it's time to move the reference revision forward.
> Move default perfcheck reference revision forward

- batchsplitter/batch_splitter.go
- batchsplitter/batch_splitter_test.go
- config/config.go
- config/config_small_test.go
- downsampler/downsampler.go
- listener/listener.go
There are 2 aspects to this change:
1. listener config validation now fails if the listener batch size is configured to be more than 1MB.
2. In the case of a series of large incoming chunks the listener batch might still exceed the 1MB limit so use the BatchSplitter to ensure that batches emitted from the listener don't exceed the limit.
To support this change, the BatchSplitter has been extracted from the downsampler package into its own.
Fixes #119.
> Ensure listener never exceeds NATS maximum message size

- README.md
- config/config.go
- config/config_small_test.go
- writer/writer.go
- writer/writer_medium_test.go
The username and password are read from two environment variables (INFLUXDB_USER and INFLUXDB_PASS).
> Support InfluxDB HTTP basic authentication

- writer/influxclient.go
- writer/writer.go
This in preparation for support write retries. 
Also reduced the maximum allowed connections. There can be many workers so each should be limited to a small number of connections. In practice each will probably only be using one HTTP connection at a time (plus another for retries).
> Extract writer's HTTP InfluxDB client code

- influx/unescape.go
- influx/unescape_small_test.go
This is about 4% faster than the previous implementation.
Closes #120
> influx: Faster Unescape implementation

- README.md
- cmd/influx-spout/e2e_large_test.go
- filter/filter.go
- filter/rules.go
- writer/writer.go
Document the metrics exposed by each influx-spout component. Also fixed a few minor issues discovered while writing these docs.
Closes #122.
> Document metrics

- writer/writer.go
- writer/writer_medium_test.go
When writing a batch to InfluxDB it is possible for the batch size to
exceed the maximum batch size because incoming lines are unlikely to
exactly fit inside the desired batch size. A BatchSplitter is now used
to ensure that the configured batch size is never exceeded.
This is important because InfluxDB has a maximum body size that it
will accept.
> writer: Enforce maximum batch size

- batch/batch.go
- batch/batch_small_test.go
The batch buffer was only being grown when there were less than 1024
bytes remaining. This was problematic in ReadOnceFrom where there
could be up to 64KB available to read (from a UDP socket), and could
result in incomplete reads.
The batch is now grown when there's less than 64KB available in the
buffer. The batch is now always grown by at least 64KB (in case a very
small batch size is configured).
> batch: Grow by at least max UDP packet size

- batch/batch.go
- batch/batch_small_test.go
ReadFrom and ReadOnceFrom would both increment the write count when no data was read from the source. For the UDP listener especially this would cause batches to get sent on sooner than intended.
> batch: Write count shouldn't increment count when no data

- downsampler/avgbucket.go
- downsampler/avgbucket_small_test.go
- influx/tags.go
- influx/token.go
- influx/token_small_test.go
A few things here:
* Instead of having Token take a boolean to control unescape handling, have a separate `TokenEscaped`  function. This leads to clearer and less errorprone code (no guessing what the boolean does).
* Fix the downsampler's handling of escaping in field keys. Field keys were being emitted unescaped when escaping was required. This is similar to the fix in #137.
* Extend test coverage for downsampler escape handling
> More escaping fixes

- .gitignore
- .travis.yml
- HACKING.md
* Release instructions: use annotated tag. The example command was incorrect.
* Bump Go versions to test with
* Git ignore files which are generated during release deploys
> Release tweaks

- README.md
- config/config.go
- config/config_small_test.go
- writer/influxclient.go
- writer/writer_medium_test.go
Aims to address #145 .
The golang net/http client already supports https, so it does not seem that additional work would be needed there.
This simple and optional configuration setting adds https capability.
> Add configuration switch for InfluxDB Writer via http and https
